print("this is 1st line")
print('this is 2nd line')
print('add header')
print('add hero section')
print('add about section')
print('add schedual section')
print('add form section')
print('add training section')
print('add it section')
print('add nav list by haneen')
print('fix picture frame by haneen')
print('add footer section')
print('add contact information')
